//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LottoGather
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LottyDBEntities : DbContext
    {
        public LottyDBEntities()
            : base("name=LottyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Powerball_Numbers> Powerball_Numbers { get; set; }
        public virtual DbSet<MegaMillions_Numbers> MegaMillions_Numbers { get; set; }
    }
}
